### ISSUE TITLE
Some accessibility issues associated with the site

### ISSUE THREAD

**Issue by mgifford** [Green-Software-Foundation/champions#1]
Lots of repetition, but good to get this fixed prior to launch. 

[Archive.zip](https://github.com/Green-Software-Foundation/speakers/files/13208861/Archive.zip)
[summary.pdf](https://github.com/Green-Software-Foundation/speakers/files/13208862/summary.pdf)

Nearly 400 instances of - Elements must meet minimum color contrast ratio thresholds
60 instances of - Links must have discernible text
44 instances of - Images must have alternate text

From a quick review, lots of these seem to be coming from common places so it shouldn't be too difficult to fix up.

**Comment by zanete** [comment]
@osamajandali please formulate the technical questions we need to answer to come up with a solution

**Comment by osamajandali** [comment]
it turns out that the problem is only on grey color that I handled already before on the GSF website. I'll work on it, no major changes should happen only darken the semi-dark greys

**Comment by adamj89** [comment]
Thanks @osamajandali 
@mgifford thanks for your patience on this. Would you mind running the test again when you have some time? Really appreciate you bringing this to our attention
