### ISSUE TITLE
Problem with the Champions deployment pipeline

### ISSUE THREAD

**Issue by russelltrow** [Green-Software-Foundation/champions#131]
# Context

There appears to be a problem with the Build stage of the Champions deployment pipeline. It appears that a missing image is causing an error

https://github.com/Green-Software-Foundation/champions/actions/runs/11152564882/job/30998404669#step:3:184

![Screenshot 2024-10-10 at 15 38 12](https://github.com/user-attachments/assets/9ea72a19-5a0d-40d6-a802-23b2894b9ebb)

It appears to be impacting all recent builds - https://github.com/Green-Software-Foundation/champions/actions

cc: @LieneKal 

# Actions

- [ ] @osamajandali resolve the error

**Comment by zanete** [comment]
@osamajandali will try to look at this today or tomorrow 🙏

**Comment by osamajandali** [comment]
Problem fixed. It was broken github handle probably he changed his handle name

**Comment by zanete** [comment]
@russelltrow could we close this now, is all working as expected?

**Comment by russelltrow** [comment]
@LieneKal are you happy everything is now working?
