### ISSUE TITLE
Screen record a manual for how to update CHampions Profiles

### ISSUE THREAD

**Issue by zanete** [Green-Software-Foundation/champions#24]
This is for the manual for Liene/Adam who will be taking records from AirTable and turning them into PRs for approval 
- [x] how to find / download the repository 
- [x] how to create a new branch
- [x] how to make changes in VScode with a sample case
- [x] how to commit
- [x] how to make a pull request for merging into the master
- [x] Make it so only Adam, Liene, Sophie (or Osama) can merge

**Comment by osamajandali** [comment]
Here is a walkthough loom on how to create/update a record and do a PR and merge it.
https://www.loom.com/share/f2e24d90f0714bb0abd461063bd0d723?sid=6952fed4-8e21-4b1a-bf10-eecd0a82a2b3

**Comment by zanete** [comment]
@adamj89 FYI ☝

**Comment by zanete** [comment]
@zanete to review the recording
@zanete to source the github names for the chairs and leads
@adamj89 to formalise the process, including any screen recordings (of how to find things in airtable)
@zanete to schedule a meeting with Liene and Adam to discuss the update process - Tuesday

**Comment by zanete** [comment]
@osamajandali Thank you very much, I love the .dev approach, it's fabulous! 
The recording is clear and no more is needed from you, so I will remove this issue from the web board.

However, @adamj89 , this screencast shows the technical actions to take, but there are some things we need to discuss to make it into a proper part of the process

Here's the summary of the steps along with where there are gaps and points for discussion:

### To make the changes:
The location is https://github.dev/Green-Software-Foundation/champions
1. Ensure you are on the main branch
2. Create a branch - _let s discuss the naming conventions for branch creation and document them in the process_
3. Switch to the new branch
4. Make changes
5. Commit with a message - _let s discuss message requirements and document them in the process_

### To request approval and publish:
The location is https://github.com/Green-Software-Foundation/champions 
1. Create a pull request - _Let's discuss the conventions for what to enter in the Title and Description of the PR_
2. Find the relevant Approvers an their GH names 
3. Set them as reviewers
4. Wait 7 days OR review the reviewer comments and resolve case by case
5. Merge when ready
6. Check that the profile is live and updated

**Comment by zanete** [comment]
FYI @adamj89 I've added the GH usernames to all the chairs and leads that I was aware of, let me know if there are any missing still.

**Comment by adamj89** [comment]
ETA for doing this is by 22 December
