### ISSUE TITLE
City change not syncing on main directory

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/champions#30]
Hi @osamajandali 

The PR went through the other day to change Pindy's city from Potters Bar to London
https://github.com/Green-Software-Foundation/champions/pull/26

This is updated and showing on her profile but not the main directory

![image](https://github.com/Green-Software-Foundation/champions/assets/20337337/32796fef-6096-4bab-b9e9-6ef61f266e9c)
![image](https://github.com/Green-Software-Foundation/champions/assets/20337337/3d90f2b7-f97f-4ba8-99f9-7a67383d4586)

**Comment by osamajandali** [comment]
Fixed. Should not happend again, but let's keep an eye on it on the next update

**Comment by adamj89** [comment]
Thanks Osama. Keeping this updated til the next build.

**Comment by zanete** [comment]
Closing this particular issue
