### ISSUE TITLE
BUG: All submitted activities causing build failures

### ISSUE THREAD

**Issue by adamj89** [Green-Software-Foundation/champions#70]
Bug description: see build failure in https://github.com/Green-Software-Foundation/champions/actions/runs/7194308618

Is this a formatting issue again?

@zanete @osamajandali

**Comment by osamajandali** [comment]
@adamj89 Some records were missing type field. and there are other that don't handle multiple lines with "|"
refer to [commit](https://github.com/Green-Software-Foundation/champions/commit/7a7064726dbb0e22d271bf1c74172fc683fe1188) to see my changes
